const CUSTOMER_SITES = {
	iqiyizyapi_com: {
		name: '🎬-爱奇艺-',
		api: 'https://pz.v88.qzz.io/?url=https://iqiyizyapi.com/api.php/provide/vod',
		detail: 'https://iqiyizyapi.com'},
	dbzy_tv: {
		name: '🎬豆瓣资源',
		api: 'https://pz.v88.qzz.io/?url=https://caiji.dbzy5.com/api.php/provide/vod',
		detail: 'dbzy.tv'},
	tyyszy_com: {
		name: '🎬天涯影视',
		api: 'https://pz.v88.qzz.io/?url=https://tyyszy.com/api.php/provide/vod',
		detail: 'https://tyyszy.com'},
	mtzy_me: {
		name: '🎬茅台资源',
		api: 'https://pz.v88.qzz.io/?url=https://caiji.maotaizy.cc/api.php/provide/vod',
		detail: 'https://mtzy.me'},
	wolongzyw_com: {
		name: '🎬卧龙资源',
		api: 'https://pz.v88.qzz.io/?url=https://wolongzyw.com/api.php/provide/vod',
		detail: 'https://wolongzyw.com'},
	ikunzy_com: {
		name: '🎬iKun资源',
		api: 'https://pz.v88.qzz.io/?url=https://ikunzyapi.com/api.php/provide/vod',
		detail: 'https://ikunzy.com'},
	lzizy_net: {
		name: '🎬量子影视',
		api: 'https://pz.v88.qzz.io/?url=https://cj.lziapi.com/api.php/provide/vod',
		detail: 'https://lzizy.net'},
	dyttzyapi_com: {
		name: '🎬电影天堂',
		api: 'https://pz.v88.qzz.io/?url=http://caiji.dyttzyapi.com/api.php/provide/vod',
		detail: 'http://caiji.dyttzyapi.com'},
	www_maoyanzy_com: {
		name: '🎬猫眼资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.maoyanapi.top/api.php/provide/vod',
		detail: 'https://www.maoyanzy.com'},
	cj_lzcaiji_com: {
		name: '🎬量子资源',
		api: 'https://pz.v88.qzz.io/?url=https://cj.lzcaiji.com/api.php/provide/vod',
		detail: 'https://cj.lzcaiji.com'},
	a360zy_com: {
		name: '🎬360 资源',
		api: 'https://pz.v88.qzz.io/?url=https://360zy.com/api.php/provide/vod',
		detail: 'https://360zy.com'},
	collect_wolongzyw_com: {
		name: '🎬卧龙影视',
		api: 'https://pz.v88.qzz.io/?url=https://collect.wolongzyw.com/api.php/provide/vod',
		detail: 'https://collect.wolongzyw.com'},
	jszyapi_com: {
		name: '🎬极速资源',
		api: 'https://pz.v88.qzz.io/?url=https://jszyapi.com/api.php/provide/vod',
		detail: 'https://jszyapi.com'},
	www_moduzy_net: {
		name: '🎬魔都资源',
		api: 'https://pz.v88.qzz.io/?url=https://www.mdzyapi.com/api.php/provide/vod',
		detail: 'https://www.moduzy.net'},
	ffzyapi_com: {
		name: '🎬非凡资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.ffzyapi.com/api.php/provide/vod',
		detail: 'https://cj.ffzyapi.com'},
	bfzy_tv: {
		name: '🎬暴风资源',
		api: 'https://pz.v88.qzz.io/?url=https://bfzyapi.com/api.php/provide/vod',
		detail: 'https://bfzy.tv'},
	zuida_xyz: {
		name: '🎬最大资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.zuidapi.com/api.php/provide/vod',
		detail: 'https://zuida.xyz'},
	zuidazy_co: {
		name: '🎬最大点播',
		api: 'https://pz.v88.qzz.io/?url=https://zuidazy.me/api.php/provide/vod',
		detail: 'https://zuidazy.co'},
	wujinzy_me: {
		name: '🎬无尽资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.wujinapi.me/api.php/provide/vod',
		detail: 'https://wujinzy.com'},
	wujinzy_com: {
		name: '🎬无尽影视',
		api: 'https://pz.v88.qzz.io/?url=https://api.wujinapi.com/api.php/provide/vod',
		detail: 'https://wujinzy.com'},
	xinlangapi_com: {
		name: '🎬新浪资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.xinlangapi.com/xinlangapi.php/provide/vod',
		detail: 'https://xinlangapi.com'},
	wwzy_tv: {
		name: '🎬旺旺短剧',
		api: 'https://pz.v88.qzz.io/?url=https://wwzy.tv/api.php/provide/vod',
		detail: 'https://wwzy.tv'},
	api_wwzy_tv: {
		name: '🎬旺旺资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.wwzy.tv/api.php/provide/vod',
		detail: 'https://api.wwzy.tv'},
	www_subozy_com: {
		name: '🎬速播资源',
		api: 'https://pz.v88.qzz.io/?url=https://subocaiji.com/api.php/provide/vod',
		detail: 'www.subozy.com'},
	jinyingzy_com: {
		name: '🎬金鹰点播',
		api: 'https://pz.v88.qzz.io/?url=https://jinyingzy.com/api.php/provide/vod',
		detail: 'https://jinyingzy.com'},
	p2100_net: {
		name: '🎬飘零资源',
		api: 'https://pz.v88.qzz.io/?url=https://p2100.net/api.php/provide/vod',
		detail: 'https://p2100.net'},
	api_ukuapi88_com: {
		name: '🎬U酷影视',
		api: 'https://pz.v88.qzz.io/?url=https://api.ukuapi88.com/api.php/provide/vod',
		detail: 'https://www.ukuzy.com'},
	api_guangsuapi_com: {
		name: '🎬光速资源',
		api: 'https://pz.v88.qzz.io/?url=https://api.guangsuapi.com/api.php/provide/vod',
		detail: 'https://api.guangsuapi.com'},
	www_hongniuzy_com: {
		name: '🎬红牛资源',
		api: 'https://pz.v88.qzz.io/?url=https://www.hongniuzy2.com/api.php/provide/vod',
		detail: 'https://www.hongniuzy.com'},
	caiji_moduapi_cc: {
		name: '🎬魔都动漫',
		api: 'https://pz.v88.qzz.io/?url=https://caiji.moduapi.cc/api.php/provide/vod',
		detail: 'https://caiji.moduapi.cc'},
	www_ryzyw_com: {
		name: '🎬如意资源',
		api: 'https://pz.v88.qzz.io/?url=https://cj.rycjapi.com/api.php/provide/vod',
		detail: 'https://www.ryzyw.com'}
};

// 调用全局方法合并
if (window.extendAPISites) {
    window.extendAPISites(CUSTOMER_SITES);
} else {
    console.error("错误：请先加载 config.js！");
}
